#!/bin/sh

# Set DPI
xrandr --dpi 96

# Set Monitor Layout
#xrandr --output DisplayPort-1 --mode 2560x1440 --pos 1200x480 --rotate normal \
#       --output DisplayPort-2 --mode 1920x1200 --pos 0x0 --rotate left
xrandr --output DisplayPort-1 --mode 2560x1440 --pos 1200x480 --rotate normal \
       --output DisplayPort-2 --mode 1920x1200 --pos 0x0 --rotate normal


~/Scripts/wacom.sh &

[ -f ~/.profile ] && . ~/.profile
