backend = "glx";
vsync = true;
dbe = false;
glx-copy-from-front = true;
glx-swap-method = 2;
glx-no-stencil = true;
xrender-sync = true;
xrender-sync-fence = true;
dithered-present = false;
unredir-if-possible = false;
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
shadow = false;
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
log-level = "warn";

# Opacity settings
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;
menu-opacity = 1.0;
force-win-blend = false;
use-damage = true;
detect-client-opacity = false;
opacity-rule = [ "100:class_g = '*'" ];